### ISSUE TITLE
Kite does not complete for PyQt5

### ISSUE THREAD

**Issue by pianocomposer321** [kiteco/plugins#150] opened 2019-11-09 14:39 UTC
I recently made the transition from vscode to neovim. I had used Kite in vs code and so I installed it on neovim too. It seemed to work as expected until I worked on a PyQt5 project. When I import the modules, it does not suggest PyQt5 (although it does suggest PyQt4), and it does not complete any of the objects. I read on the FAQ that it said Kite will only complete modules installed in the home directory, and to try running "import module; print(module.\_\_file\_\_)". This outputted "C:\Users\\_\_\_\_\_\_\_\AppData\Local\Programs\Python\Python37\lib\site-packages\PyQt5\\\_\_init\_\_.py", which I believe is my home directory, is it not?

I am running Windows 10, Python 3.7.5 64-Bit. I don't know what Neovim version, but I think it is the latest as I only installed it a couple of days ago.

**Comment by sametyildirima** [comment] 2020-04-09 13:22
The same problem. Please, let me know if you solved

**Comment by its-dhung** [comment] 2020-04-21 03:56
Duplicate of #140

**Closed by its-dhung** 2020-04-21 03:56 UTC
