### ISSUE TITLE
PyCharm exception in supportsFileExtension

### ISSUE THREAD

**Issue by its-dhung** [kiteco/plugins#165] opened 2020-01-07 18:45 UTC
User reported an exception in PyCharm 2019.3.1

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'ext' of com/kite/intellij/lang/KitePythonSupport.supportsFileExtension must not be null
               at com.kite.intellij.lang.d.a(KitePythonSupport.java)
               at com.kite.intellij.lang.d.supportsFileExtension(KitePythonSupport.java)
               at com.kite.intellij.lang.e.a(LanguageSupportManager.java:24)
               at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
               at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
               at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
               at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
               at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
               at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
               at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
               at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
               at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
               at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
               at com.kite.intellij.lang.e.B(LanguageSupportManager.java:24)
               at com.kite.intellij.lang.c.a(KiteLanguageSupport.java:35)
               at com.kite.intellij.lang.c.b(KiteLanguageSupport.java:29)
               at com.kite.intellij.lang.psi.refs.c.a(PsiReferenceTracker.java:58)
               at com.kite.intellij.lang.psi.refs.a.doCollectInformation(CollectHighlightingPass.java:43)
               at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
               at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
               at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
               at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
               at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
               at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
               at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
               at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
               at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
               at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
               at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
               at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
               at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
               at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
               at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
               at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
               at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
               at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by jansorg** [comment] 2020-01-08 10:52
This is most likely a duplicate of https://github.com/kiteco/plugins/issues/161#issuecomment-571854958 and fixed with the latest release.

**Closed by jansorg** 2020-01-08 10:52 UTC
Labels: pycharm
