### ISSUE TITLE
[vim] Extra characters inserted

### ISSUE THREAD

**Issue by dimaqq** [kiteco/plugins#145] opened 2019-10-28 02:39 UTC
If I type fast and kite is showing a suggestion, extra characters are inserted into my file.

* there's no problem if I type s..l..o..w..l..y..
* there was no problem before I've added kite plugin

For example, if I go to the top of a file an type `O` (add line) `import logging` `Enter`, I might end up with:
`importo logging` or
`import logginge` or
`impo rt logging` or
`import logginwg`

I'm pretty sure the extra characters come from some odd interaction of Kite showing suggestions on `imp...` and `log..` etc. Perhaps it's asynchrony, i.e. if suggestions for `log` and `logg` come out of order...

```
:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  8 2019 07:17:45)
macOS version
Included patches: 1-1999
Compiled by Homebrew
```

**Comment by airblade** [comment] 2019-10-29 09:31
Please could you tell me what `:verbose set cot?` gives?

**Comment by dimaqq** [comment] 2019-10-29 09:56
```
  completeopt=menu,preview,menuone,noinsert
        Last set from ~/.vim/pack/kite/start/vim-plugin/autoload/kite.vim line 60
```

I shouldn't have other autocompletion plugins active, but I guess there's always a random chance of remnants of decrepit plugins...

**Comment by airblade** [comment] 2019-10-29 10:06
Thanks.  Hmm, I can't reproduce this, typing as fast as I can.  I'm using MacVim 8.1.1-1722 via Homebrew.

In your examples above, I presume you didn't type the `e` and the `w` yourself?

Do you know what version of the plugin you've got?  Either the SHA or `:echo kite#utils#plugin_version()`.

**Comment by dimaqq** [comment] 2019-10-31 08:45
Correct, the `e` and `w` were not typed by me...

I've disabled all other plugins, as far as I can tell:
```
:scriptnames
  1: ~/.vimrc
  2: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/syntax/syntax.vim
  3: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/syntax/synload.vim
  4: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/syntax/syncolor.vim
  5: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/filetype.vim
  6: /usr/local/Cellar/hub/2.10.0/share/vim/vimfiles/ftdetect/pullrequest.vim
  7: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/ftplugin.vim
  8: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/indent.vim
  9: ~/.vim/autoload/plug.vim
 10: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/ftoff.vim
 11: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/plugin/getscriptPlugin.vim
 12: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/plugin/gzip.vim
 13: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/plugin/logiPat.vim
 14: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/plugin/manpager.vim
 15: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/plugin/matchparen.vim
 16: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/plugin/netrwPlugin.vim
 17: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/plugin/rrhelper.vim
 18: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/plugin/spellfile.vim
 19: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/plugin/tarPlugin.vim
 20: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/plugin/tohtml.vim
 21: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/plugin/vimballPlugin.vim
 22: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/plugin/zipPlugin.vim
 23: ~/.vim/pack/kite/start/vim-plugin/plugin/kite.vim
 24: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/syntax/python.vim
 25: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/ftplugin/python.vim
 26: /usr/local/Cellar/vim/8.1.2200/share/vim/vim81/indent/python.vim
 27: ~/.vim/pack/kite/start/vim-plugin/autoload/kite.vim
 28: ~/.vim/pack/kite/start/vim-plugin/autoload/kite/utils.vim
 29: ~/.vim/pack/kite/start/vim-plugin/autoload/kite/async.vim
 30: ~/.vim/pack/kite/start/vim-plugin/autoload/kite/events.vim
 31: ~/.vim/pack/kite/start/vim-plugin/autoload/kite/client.vim
 32: ~/.vim/pack/kite/start/vim-plugin/autoload/kite/status.vim
 33: ~/.vim/pack/kite/start/vim-plugin/autoload/kite/onboarding.vim
 34: ~/.vim/pack/kite/start/vim-plugin/autoload/kite/completion.vim
 35: ~/.vim/pack/kite/start/vim-plugin/autoload/kite/snippet.vim
 36: ~/.vim/pack/kite/start/vim-plugin/autoload/kite/signature.vim
Press ENTER or type command to continue
```

kit plugin version: `1.0.48`

**Comment by airblade** [comment] 2019-11-01 10:35
Ok, thanks.  I'm not sure what this could be.

Do you have any insert-mode maps or abbreviations?  What do `:imap` and `:iab` produce?

**Comment by dimaqq** [comment] 2019-11-06 06:16
Only one for `:imap`
`!  <D-v>         <C-R>*`

Before I've removed other plugins, I also had:
`i  <Plug>(ale_complete) * <C-\><C-O>:ALEComplete<CR>`

nothing for `:iab`.

I've now had to uninstall `Kite` app 😭because well, I really need my editor to insert what I type!

**Comment by airblade** [comment] 2019-11-06 12:15
I wonder if there's any chance you could have triggered Ale's completion while typing?  According to the docs [here](https://github.com/dense-analysis/ale/blob/2d9380d75c5c27a3241925d24ab3be8977a43207/doc/ale.txt#L2571) `<C-Space>` would do it.

Although of course that certainly couldn't happen once Ale was uninstalled.

Hmm, I'm still baffled.

> I really need my editor to insert what I type!

I understand :)

**Comment by airblade** [comment] 2019-11-06 15:10
By the way, are you using MacVim as a GUI app or in the terminal?  If in the terminal, which terminal do you use?

Thank you.

**Comment by dimaqq** [comment] 2019-11-06 22:43
iTerm2

**Comment by airblade** [comment] 2020-01-08 15:38
This was fixed in https://github.com/kiteco/vim-plugin/pull/249 so I'm going to close this now.  Let me know if you have any further trouble.

**Closed by airblade** 2020-01-08 15:38 UTC
