### ISSUE TITLE
Kite for Spyder Ide

### ISSUE THREAD

**Issue by amith1108** [kiteco/plugins#122] opened 2019-02-06 03:22 UTC
Hi,

Will there be a kite version for Spyder Ide, as I use Spyder for my development. Is there any way to integrate Kite with Spyder on Ubuntu.

Thanks

**Comment by Mte90** [comment] 2019-05-03 11:22
ping for this!

**Comment by Mte90** [comment] 2019-05-03 11:38
duplicate of https://github.com/kiteco/plugins/issues/119

**Comment by caelan-kite** [comment] 2020-01-31 20:05
Hi @amith1108 & @Mte90 , Spyder + Kite support was released as part of the Spyder 4 release. [More info here](https://kite.com/blog/product/announcing-kite-for-spyder-4/). 

Looking forward to your feedback once you try it, or if you've already tried it out!

Also, if you find bugs, it's best to post them in [Spyder's repo here](https://github.com/spyder-ide/spyder/issues) so both the Spyder and Kite teams can collaborate on them.

**Closed by caelan-kite** 2020-01-31 20:05 UTC
